[build]
builder = "nixpacks"

[deploy]
startCommand = "python run_bot.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8001"
